# ???? ??
# https://curiousjinan.tistory.com/entry/spring-boot-tomcat-environment
jwt:
  # ????
  header: Authorization
  # jwt ??? ?? salt
  secret: ${JWT_SECRET}
  # ????
  expire_time: 600 # 10 min

spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  thymeleaf:
    cache: false
  security:
    user:
      name: user
      password: password
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create
    show-sql: true
    # table create 후 data.sql initialize
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

naver:
  developers:
    client-id: ${NAVER_DEVELOPERS_CLIENT_ID}
    client-secret: ${NAVER_DEVELOPERS_CLIENT_SECRET}
  ncp:
    client-id: ${NCP_CLIENT_ID}
    client-secret: ${NCP_CLIENT_SECRET}
    

kto:
  serviceKey: ${KTO_SERVICE_KEY}

springdoc:
  swagger-ui:
    display-request-duration: true
  api-docs:
    path: /v1/api-docs

  paths-to-match:
    - /api/v1/**