jwt:
  # ????
  header: Authorization
  # jwt ??? ?? salt
  secret: ${JWT_SECRET}
  # ????
  expire_time: 600 # 10 min

spring:
  security:
    user:
      name: user
      password: password
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}



  jpa:
    hibernate:
      format_sql: true
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}