name: Auto Assign PR Creator and Random Reviewers

on:
  pull_request:
    branches: [dev]
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      issues: write
    steps:
      - name: 'Assign Random Reviewers'
        uses: actions/github-script@v5
        with:
          script: |
            const reviewers = ['changyukim98', 'illa0306', 'm1nddoong', 'PJScript', 'sieunq'];
            const shuffled = reviewers.sort(() => 0.5 - Math.random());
            const selectedReviewers = shuffled.slice(0, 3);

            github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              reviewers: selectedReviewers
            });
          github-token: ${{ secrets.GITHUB_TOKEN }}
